name: tech
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  build_runner: ^2.4.13
  validators: ^3.0.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  flutter_widget_from_html: ^0.15.3
  get_storage: ^2.1.1
  file_picker: ^8.3.1
  html_editor_enhanced: ^2.6.0
  just_audio: ^0.9.46
  percent_indicator: ^4.2.4
  audio_video_progress_bar: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


# pubspec.yaml
flutter_gen:
  integrations:
    flutter_svg: true

flutter:


  uses-material-design: true

  
  assets:
    - assets/icons/bluemic.png
    - assets/icons/bluepen.png
    - assets/icons/hashtagicon.png
    - assets/icons/home.png
    - assets/icons/techbot.svg
    - assets/icons/emptytcbot.svg
    - assets/icons/user.png
    - assets/icons/write.png
    - assets/icons/down_cat_arrow.png
    - assets/icons/write_article.png
    - assets/icons/write_podcast.png
    - assets/images/avatar.png
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/podycast.png
    - assets/images/radiocodeyad.png
    - assets/images/ramzon.png
    - assets/images/tecnocast.png
    - assets/images/postertest.png
    - assets/images/single_place_holder.jpg

    
          

